// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuCoresUsage() {
  return window['go']['main']['App']['GetCpuCoresUsage']();
}

export function GetCpuUsage() {
  return window['go']['main']['App']['GetCpuUsage']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}
