// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysinfo} from '../models';

export function GetCpuCoresUsage():Promise<Array<number>>;

export function GetCpuUsage():Promise<number>;

export function GetSystemInfo():Promise<sysinfo.SystemInfo>;
